---
- name: "Wordpress installation using ansible"
  become: true
  hosts: all
  vars_files:
   - variables.yml
  tasks:

    - name: "Apache - Installing Apache"
      yum:
        name:
          - httpd
        state: present

    - name: "Apache - Installing php module"
      shell: amazon-linux-extras install php7.4 -y

    - name: "Apache - Copying Configuration File"
      template:
        src: httpd.conf.tmpl
        dest: /etc/httpd/conf/httpd.conf
      register: config_status

    - name: "Apache - Adding VirtaulHost Entry"
      template:
        src: virtualhost.conf.tmpl
        dest: /etc/httpd/conf.d/{{httpd_hostname}}.conf
      register: vhost_status

    - name: "Apache - Creating Documentroot Directory"
      file: 
        path: "{{doc_root}}"
        state: directory
        owner: "{{httpd_owner}}"
        group: "{{httpd_group}}"

    - name: "Apache - Restarting/Enabling Apache"
      when: config_status.changed == true or vhost_status.changed == true
      service:
        name: httpd
        state: restarted
        enabled: true

    - name: "Mariadb-Server - Package Installing"
      yum:
        name:
          - mariadb-server
          - MySQL-python
        state: present

    - name: "Mariadb-Server - Service Restart/Enabling"
      service:
        name: mariadb
        state: restarted
        enabled: true

    - name: "Maiadb-Server - Updating Root Password"
      ignore_errors: true
      mysql_user:
        login_user: "root"
        login_password: ""
        user: "root"
        password: "{{mariadb_root_password}}"
        host_all: true

    - name: "Mariadb-Server - removing anonymous users"
      mysql_user:
        login_user: "root"
        login_password: "{{mariadb_root_password}}"
        user: ""
        password: ""
        host_all: true
        state: absent

    - name: "Mariadb-Server - Creating database"
      mysql_db:
        login_user: "root"
        login_password: "{{mariadb_root_password}}"
        name: "{{mariadb_extra_database}}"
        state: present

    - name: "Mariadb-Server - Creating User"
      mysql_user:
        login_user: "root"
        login_password: "{{mariadb_root_password}}"
        user: "{{mariadb_extra_user}}"
        password: "{{mariadb_extra_password}}"
        host: "localhost"
        state: present
        priv: '{{mariadb_extra_database}}.*:ALL'

    - name: "Wordpress - Downloading Archive file"  
      get_url:
        url: "{{wp_url}}"
        dest:  /tmp/wordpress.tar.gz

    - name: "Wordpress - Extracting Archive file"
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /tmp/
        remote_src: true

    - name: "Wordpress - Copying Contents To DocumentRoot"
      copy:
        src: /tmp/wordpress/
        dest: "{{doc_root}}"
        owner: "{{httpd_owner}}"
        group: "{{httpd_group}}" 
        remote_src: true

    - name: "Worpress - Creating wp-config.php file"
      template:
        src: wp-config.php.tmpl
        dest: "{{doc_root}}/wp-config.php"

    - name: "Post-installation restart"
      service:
        name: "{{item}}"
        state: restarted
      with_items:
        - httpd
        - mariadb
